# Site settings
title: kubevirt.io
email: non@none.com
description: > # this means to ignore newlines until "baseurl:"
  Virtual Machine Management on Kubernetes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kubevirtgithubio-kubevirt-test.6923.rh-us-east-1.openshiftapps.com/" # the base hostname & protocol for your site
twitter_username: kubevirt
github_username:  kubevirt
irc: kubevirt@irc.freenode.net
Mailinglist: https://groups.google.com/forum/#!forum/kubevirt-dev
events: 18pc0jur01k8f2cccvn5j04j1g@group.calendar.google.com
kubevirt_version: v0.7.0-alpha.2

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
gems:
  - jekyll-paginate
  - html-proofer
  - kramdown
  - github-pages

plugins_dir: [jekyll-paginate]
paginate: 10
paginate_path: "/blog/page:num"

collections:
  docs:
    permalink: "/:collection/:slug"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs

mycategories:
  - "introduction": "/docs/introduction/" 
  - "installation": "/docs/installation/"
  - "usage": "/docs/usage/"
  - "authorization": "/docs/authorization/"
  - "virtual machines": "/docs/virtual-machines/"
  - "controllers": "/docs/controllers/"
  - "templates": "/docs/templates/"
  - "additional resources": "/docs/additional-resources/"
